### ISSUE TITLE
Time-dependent problem at de Gerlache crater

### ISSUE THREAD

**Issue by sampotter** [sampotter/python-flux#55]
@steo85it 

What has been done with this so far? I would like to push this along

**Comment by sampotter** [comment]
Added start of example to `./examples/gerlache` in a15604778b379111e80331820cbb2c0d2066de99.

This will download Mike's DEM from PGDA ([here](https://pgda.gsfc.nasa.gov/products/81)) and convert it to a .npy file which can be easily memory-mapped.

Next to do: make a Delaunay mesh of de Gerlache.

**Comment by steo85it** [comment]
I'm running it, making meshes at different resolutions, etc ... on my side, setting up a clear script to run the example at different resolutions and compare results (which ones? fluxes? T?) to some ground-truth (non-compressed FF) is the next step.

**Comment by sampotter** [comment]
Gotcha. I like the look of these plots, they are interesting. How big are these meshes? And where are the scripts you're currently using? It will be helpful if you can share the code you use to call SPICE to generate sun positions.

**Comment by steo85it** [comment]
It's all here [run_lsp.py](https://github.com/steo85it/plapp-flux/blob/9595e6b10de7f52ec4674aa5fe465a95e5ced6e7/examples/lsp/run_lsp.py)
I have to figure out how to unpack this (and especially the large [proc_objfil.py](https://github.com/steo85it/plapp-flux/blob/9595e6b10de7f52ec4674aa5fe465a95e5ced6e7/plapp/proc_objfil.py) which it calls) and include it in a structure such as the one you set up in the `./examples/gerlache` (which is quite useful to have as a basis to do it).

**Comment by steo85it** [comment]
About the code for SPICE, these [lines](https://github.com/steo85it/plapp-flux/blob/9595e6b10de7f52ec4674aa5fe465a95e5ced6e7/plapp/proc_objfil.py#L113-L127) should be useful. [These](https://github.com/steo85it/plapp-flux/blob/9595e6b10de7f52ec4674aa5fe465a95e5ced6e7/plapp/proc_objfil.py#L271-L297). (Btw, I made a few adjustments for paths, etc... today. I'll push them if useful, but it doesn't change much.)

**Comment by steo85it** [comment]
> How big are these meshes?

This one was a small test. Barely 2500 triangles with a resolution of 500 mpp. I'm running one at 250 mpp, but I should start to save some statistics. Let me check if it's easy to integrate things in your cleaner structure.
Also, I noticed that I get in trouble loading point-clouds from Mike's 5mpp mesh (at least on my laptop) ... it's probably best using a downsampled version of it to 20 or 50 mpp (anyway, we won't be able to use meshes down to 5mpp for a whole crater). I'll make one with gdal and load it.

**Comment by steo85it** [comment]
For a start, I'd replace the content of `convert_geotiff_to_npy.py` and `make_mesh.py` by [these](https://github.com/steo85it/plapp-flux/blob/c09a29b59fb825942839da4be4cda08f25f27903/examples/deGerlache/run_lsp.py#L49-L67) lines (in one or 2 files, whatever is clearer). I'll do it after dinner, if that's ok for you (we can simplify by skipping the outer/inner mesh, if we don't plan to focus on occultations from far away topography - not sure that's relevant for the paper - and also set the coordinates to cut as input parameters).

**Comment by steo85it** [comment]
See updates in [gerlache branch in github/python-flux](https://github.com/sampotter/python-flux/tree/gerlache/examples/gerlache) for the steps you mentioned (generate mesh - resolution is argument - and convert to cartesian).
Now the FF can be generated and illuminated using tools from other examples, I think.

**Comment by sampotter** [comment]
I see the imperfections. Since there are speckles in the first plot, I guess it has to do with using Embree?

So that I understand: to make your mesh, you load Mike's DEM as a point cloud and then use a tool to convert a point cloud into a 3D mesh?

I was planning on using meshpy with a user refinement function which checks the area of each 3D triangle. This way it should be possible to use one threshold inside an ROI containing the crater, and another outside for coarse-grained occlusion.

I have to run some errands until early afternoon today (going to get ultrasound #2 of our baby :o) but will be back later.

**Comment by steo85it** [comment]
> So that I understand: to make your mesh, you load Mike's DEM as a point cloud and then use a tool to convert a point cloud into a 3D mesh?

I **load a downsampled** (to 50mpp, with `gdal_translate ldem_87s_5mpp.tif -tr 50 50 ldem_87s_50mpp.tif`) version of Mike's **DEM**, **cut** out the part that I need (interactively or not), indeed **convert it to a point-cloud**, then use Open3D (https://towardsdatascience.com/5-step-guide-to-generate-3d-meshes-from-point-clouds-with-python-36bad397d8ba, Poisson method) to **get the mesh at whatever resolution** (>=50mpp, in this case). 

> I was planning on using meshpy with a user refinement function which checks the area of each 3D triangle. This way it should be possible to use one threshold inside an ROI containing the crater, and another outside for coarse-grained occlusion.

I got a bit annoyed with meshpy, dmesh etc since they are really slow at high-resolution. Open3D is super fast (I have to check how good/regular/water-tight the mesh is). Also, **you might get in trouble if you do what you plan to**, because of "holes" at the transitions between outer and inner mesh. I solved it by meshing the whole DEM at the target resolution, then cutting out the inner DEM (it's in the code I linked yesterday, I didn't copy it to the example because I don't think it's really relevant for the paper).

> I have to run some errands until early afternoon today (going to get ultrasound #2 of our baby :o) but will be back later.

That's super cool, enjoy and congrats! (great that they let you in, too, in these covid times) :)

**Comment by nschorgh** [comment]
To avoid any interpolation from occurring I simply do this to generate a mesh:
```
    points_mesh = a[:,:2]   # mesh based on (x,y)  
    triangulation = scipy.spatial.Delaunay(points_mesh)  
    V, F = triangulation.points, triangulation.simplices
    V = np.row_stack([V.T, a[:,2]]).T   # add z to vertex coordinates
```
where I might create (x,y) from a raster. It's surprisingly fast (used it for millions of points), avoids loss of accuracy due to interpolation, and works for all quad-tree situations. We want to triangulate an existing point cloud, not create any other type of mesh.
gdal_translate is presumably good at downsampling a raster.

**Comment by steo85it** [comment]
Yes, that was the other option: using `gdal` libraries to read and downsample the mesh within the code
```
from osgeo import gdal
ds = gdal.Open('input.tif')
ds = gdal.Translate('output.tif', ds, xRes, yRes)
```
and then do what @nschorgh suggests. For my applications, I still think my approach is more flexible, but maybe here we can cut part of Mike's GTiff and process it in this way w/o importing many libraries.

**Comment by sampotter** [comment]
I am not convinced by either of your approaches to meshing. Sorry... :-(

Please see the script [make_mesh_sfp.py](https://github.com/sampotter/python-flux/blob/gerlache/examples/gerlache/make_mesh_sfp.py) in the gerlache branch. It creates a 40K triangle mesh of the region [-25, 25] x [-25, 25] (stereo x/y) in 42 seconds on my computer. This uses [Shewchuk's Triangle](https://www.cs.cmu.edu/~quake/triangle.html) via [MeshPy](https://documen.tician.de/meshpy/) with a refinement function `should_refine` (max area in km^2 of the 3D triangle).

This seems like a reasonable amount of time to wait for a triangle mesh since we will spend *much* more time on the backend actually solving the problem. Maybe it would make sense to compare the amount of time it takes to construct the mesh with the compressed FF matrix assembly time.

Some details:
1) this loads the original 5 mpp DEM as a memory-mapped file so the whole DEM doesn't need to be loaded to memory
2) it uses linearly interpolation to look up subpixel values from the original DEM
3) it builds the Delaunay mesh in the **stereographic x/y** plane
4) for refinement, it maps each stereographic triangle to Cartesian coordinates and computes the area

Here is a screenshot of the resulting mesh:

![image](https://user-images.githubusercontent.com/6035363/150383898-de5765f1-42eb-414b-898e-8ef793dc68d2.png)

> That's super cool, enjoy and congrats! (great that they let you in, too, in these covid times) :)

Thanks. We are very excited. :-)

**Comment by steo85it** [comment]
Not a problem, and whatever you like to use is fine. Still, for what matters, I think steps 1 and 2 should be improved.
I would definitely use the `xarray` package to load the map, clip it, resample it (we said that we don't want interpolation, and I guess even less a linear interpolation) and eventually reproject it. It's optimized for that and it would make the code cleaner (and it's a really basic package for mapping and such + it has some really cool options for multidimensional datasets analysis and visualization).
Once you have the DEM portion you want in memory (steps 1-2), I'm fine with meshing it up as you are doing.

**Comment by sampotter** [comment]
No problem! Of course if your methods end up being better, we should use those instead! I am not familiar with xarray, rasterio, or Open3D. It takes me a while to pick up new libraries, so I like to stick with what I know if I can. Sorry, some inertia on my part...

I'd like to understand your objection to using interpolation a bit better. I made some plots using [a script I just pushed](https://github.com/sampotter/python-flux/blob/gerlache/examples/gerlache/dem_error.py):

![image](https://user-images.githubusercontent.com/6035363/150395140-578dedd1-2bc9-4280-bc48-cdc6ab49c9af.png)
![image](https://user-images.githubusercontent.com/6035363/150395179-872c390b-dc40-43cd-8fc5-cad2c7b7aaad.png)

The first plot is just the DEM for a small 100x100 patch. The second two plots show the first differences along each axis in centimeters. The third plot shows the histograms of the first and second differences, with the DEM's error bars (as I understand them) included. From [the DEM's website](https://pgda.gsfc.nasa.gov/products/81), "this 87-90 deg mosaic product has a typical RMS residual of 30-55 cm with the individual fields".

When I look at these plots, my instinct is: "Yes, it's 100% fine to use linearly interpolation to access subgrid values *at the original grid resolution*. You will incur some error but it is very unlikely to exceed the existing DEM error due to the regularity of the field being sampled. Using anything higher order than linear interpolation is a waste because DEM error dominates and the surface itself is not meaningfully smooth (but it is continuous)."

On the other hand, if you first upsample the grid (say, by a factor of 10), then linearly interpolate to access subgrid values, you will certainly incur an error much larger than the stated 30-55 cm. Of course, this will also happen at non-vertex points if you generate a very coarse mesh. But by linearly interpolating at the original 5 mpp resolution, you can at least have some confidence in the vertices, which means that if you refine, you can expect to match the DEM if you go fine enough.

So in my mind it makes sense to just access the (very high quality!) DEM directly and use linear interpolation to look up subgrid values. This is cheap, easy, and straightforward.

**Comment by sampotter** [comment]
Here is a couple more screenshots showing what I'm after:

![image](https://user-images.githubusercontent.com/6035363/150414058-1d53f824-f6ac-44f3-9a16-4c76bd00caf2.png)
![image](https://user-images.githubusercontent.com/6035363/150414205-cbff68a0-5b82-4add-ac17-2a655f72d8f8.png)

This uses a refinement function which uses a constant target triangle area "inside" Gerlache, and then uses a linear ramp outside of the crater. This is a mesh with 10k faces. Probably there's a smarter choice of refinement function, but this gets the idea across.

This is all one triangle mesh. Only a very small number of triangles are used to extend the mesh for occlusion.

**Comment by steo85it** [comment]
Wow, this looks great, thanks. And if there aren't irregularities at the boundary between the "inner" and "outer" region, it should work well, too! Also, indeed your plots seem to show that there is no problem saving an interpolated version of the data. 
Ok, if everything already works fine w/o importing other libraries or playing too much with reference frames, I'm also fine with it (especially since we are looking at a specific single case).

**Comment by nschorgh** [comment]
@sampotter 
Linear interpolation will dull a ridge, unless the points on the ridge are kept. For our application that would be bad indeed. 

Lots of labor often goes into the construction of DEMs. Construction of this particular DEM was a paper by itself. Some spend many hours constructing DEMs from shadows and altimeter foot prints. For one project I'm involved in, someone will spend 1400 hours to improve the DEMs of a handful of crates on Ceres. 

So, DEM points can contain precious information. To demonstrate the computational power of a method this doesn't matter, but if one wants accurate shadows and temperatures, giving up original grid points would be an unwanted and unnecessary loss of information.

**Comment by sampotter** [comment]
I agree with that.

My point is that in terms of dulling a ridge, linearly interpolating the DEM at the original resolution (5 mpp) is much less likely to dull a ridge than linearly interpolating a downsampled DEM (50 mpp). I also don't think there is any reason to use higher order interpolation at the 5 mpp resolution because of noise.

If necessary a list of vertices to fix in the triangulation can be inserted using MeshPy, I think. Probably not worth including for the current paper.

**Comment by steo85it** [comment]
Is it normal to get this issue when running `try_time_dependent_problem.py` with the `FF.bin` produced by `make_form_factor_matrices.py`?
```
Traceback (most recent call last):
  File "/home/sberton2/Lavoro/code/python-flux/examples/gerlache/try_time_dependent_problem.py", line 71, in <module>
    hit = shape_model.intersect1(x, d)
  File "/home/sberton2/Lavoro/code/python-flux/src/flux/shape.py", line 133, in intersect1
    return self._intersect1(x, d)
  File "/home/sberton2/Lavoro/code/python-flux/src/flux/shape.py", line 257, in _intersect1
    return self.aabb.intersect1(x, d)
AttributeError: 'flux.cgal.aabb.AABB' object has no attribute 'intersect1'
```

**Comment by sampotter** [comment]
The start of the Gerlache crater example now uses `flux.model.ThermalModel`. See [try_time_dependent_problem.py](https://github.com/sampotter/python-flux/blob/gerlache/examples/gerlache/try_time_dependent_problem.py).

I just picked any old physical parameters I could steal from other scripts to get this to work (mostly from examples-old/lsp_illuminate.py). I would like to massage this script into something that will generate the data we need for the paper.

I am going to ignore whether this model makes any sense for now and move on to finishing the setup of the example:
- [ ] run this for different FF matrices (true vs compressed w/ varied tol, and for different mesh sizes)
- [ ] do comparisons of the temperatures over time
- [ ] make plots comparing RMS error of T over time
- [ ] make plots comparing T pointwise at some depth far out in time (to get qualitative sense of the error fields---e.g. are they smooth?)
- [ ] also would be cool: make a plot which shows % of time taken by each task (insolation, compute T, ...)

At the same time we should:
- [ ] fix the parameters to make it more realistic
- [ ] include actual sun positions
- [ ] try for a "global" problem such as Vesta

Here are some videos from layers 0 through 3. Skin depths are 0.1 mm apart. Color range is from 99 K to 128 K.

https://user-images.githubusercontent.com/6035363/151057841-0e3f8fb9-1adb-4b6e-9724-5ebe10cda5c9.mp4

https://user-images.githubusercontent.com/6035363/151057936-78ab245e-849d-433a-8ee3-4038bf2073e2.mp4

https://user-images.githubusercontent.com/6035363/151058007-939d34a6-9892-4f04-8297-513cf6d0b61c.mp4

https://user-images.githubusercontent.com/6035363/151058041-be07bfb5-3a8c-4ee5-8406-1f1a4173ea8b.mp4

**Comment by sampotter** [comment]
> Is it normal to get this issue when running `try_time_dependent_problem.py` with the `FF.bin` produced by `make_form_factor_matrices.py`?
> 
> ```
> Traceback (most recent call last):
>   File "/home/sberton2/Lavoro/code/python-flux/examples/gerlache/try_time_dependent_problem.py", line 71, in <module>
>     hit = shape_model.intersect1(x, d)
>   File "/home/sberton2/Lavoro/code/python-flux/src/flux/shape.py", line 133, in intersect1
>     return self._intersect1(x, d)
>   File "/home/sberton2/Lavoro/code/python-flux/src/flux/shape.py", line 257, in _intersect1
>     return self.aabb.intersect1(x, d)
> AttributeError: 'flux.cgal.aabb.AABB' object has no attribute 'intersect1'
> ```

I added a new function `intersect` to that class... Make sure to pull all changes and rebuild everything. Also double check that the `AABB` class does indeed have `intersect`, otherwise something got out of sync...

**Comment by nschorgh** [comment]
I would do the error/convergence test for de Gerlache with the equilibrium temperature - that's much faster and to the point.

**Comment by steo85it** [comment]
Are those at equilibrium? Probably not, and do we want to comment on getting there, in the paper?

**Comment by sampotter** [comment]
No, definitely not at equilibrium. Getting to equilibrium is outside the scope of the paper.

> I would do the error/convergence test for de Gerlache with the equilibrium temperature - that's much faster and to the point.

I'll make a note to do these, too.

Since the claim is that we can use the compressed FF matrix to solve the time-dependent problem more quickly, I think it would be useful to try to get a rough idea of what the error incurred by doing so is. I think it should be quite small.

**Comment by nschorgh** [comment]
With equilibrium I simply mean epsilon*sigma*T^4 = B (the surface temperature is in equilibrium with the incoming radiance, no subsurface heat flux). Convergence with spatial resolution.

**Comment by sampotter** [comment]
Yes of course --- we are talking about two different things. You were suggesting plots made w/o subsurface flux and Stefano was just asking whether the simulation had run long enough for the temperature to reach equilibrium in the videos I attached.

**Comment by steo85it** [comment]
a2504bc should address using real sun positions from SPICE

**Comment by sampotter** [comment]
Here's a quick error test _without_ subsurface heat conduction... Need to figure out what the most sensible way to do this is.

To make these plots, I sampled the temperature values on a regular grid by setting up an orthographic camera pointing at the crater, and traced a ray for each pixel. I then look up the temperature value based on which triangle was hit. I am not sure this is the best way to do this, but this is the first idea I had.

---

**Test 1**

Here is `T` with the max inner area set to 0.4 and the max outer area set to 3.0, compared between the compressed FF matrix with `tol = 1e-2` and the true FF matrix (percentage error, i.e. `100*|\hat{T} - T|/|T|`):

![image](https://user-images.githubusercontent.com/6035363/151204615-10e73e3c-cb65-4689-b5af-99deb348566f.png)

The same thing but with `tol = 1e-1` instead of `1e-2`:

![image](https://user-images.githubusercontent.com/6035363/151204733-a468ac1f-8708-4d61-b5c7-32815fd911ee.png)

In both cases, the max % error is set to 10 on the colorbar, so actually there is quite an improvement here when using a lower tolerance.

---

**Test 2**

The same as the first plot from Test 1, except that for the compressed FF matrix we instead set the inner area to 0.75, so that a different mesh is used (again, % error clamped to 10%):

![image](https://user-images.githubusercontent.com/6035363/151205160-d82ba594-f8aa-4c1f-afd3-f7489dcf3816.png)

You can see wherever there is a ridge, there is quite a lot of error in the solution. This is understandable. On the ridge, the orientation of the triangles will change significantly, which alters the solution there dramatically. Meshes for two different finenesses only roughly agree in space. Comparing solutions on two different meshes isn't straightforward, I don't think. Even if you use a mesh taken from a regular grid with different grid spacing, you will have the same problem.

To address this, we should probably use curved elements and higher-order basis functions (e.g., linear at least) instead of flat triangles + constant basis functions. This is a substantive amount of work which could be addressed in another paper, I think. In such a paper we would also want to decide what the correct way to "conservatively interpolate" solutions between meshes is.

---

I think it makes sense to include Test 1 but not Test 2. That is, we should check the agreement between the true FF matrix and compressed FF matrix for different tolerances, but doing a convergence study at this point may be premature. Unless we want to do something simpler, like just compare the average temperatures or some other bulk statistics.

What do you guys think?

**Comment by sampotter** [comment]
There are two separate orthogonal questions here:

1. Whether triangles + constant basis functions + our view factor approximation (midpoint rule) is a reasonable discretization of the radiosity integral equation for the thermal modeling task at hand
2. Whether our algorithm accurately approximates the true system matrix for the discretization in (1)

The answer to (2) is "yes" based on numerical evidence we are able to provide.

The answer to (1) is outside the scope of the paper, IMO.

**Comment by sampotter** [comment]
> [a2504bc](https://github.com/sampotter/python-flux/commit/a2504bc5c0be3fc4482b56e0f2814398d617c90b) should address using real sun positions from SPICE when [this option](https://github.com/sampotter/python-flux/blob/a2504bc5c0be3fc4482b56e0f2814398d617c90b/examples/gerlache/try_time_dependent_problem.py#L30) is True (it's not yet thoroughly tested, and feel free to change things you don't like, but the results look reasonable and if vertices are given in cartesian coordinates, it should be fine)

This is perfect, thanks!

**Comment by steo85it** [comment]
> I think it makes sense to include Test 1 but not Test 2. That is, we should check the agreement between the true FF matrix and compressed FF matrix for different tolerances, but doing a convergence study at this point may be premature.

I would agree that our goal is to assess the performance of the FF compression (1), rather than of different kinds/choices of meshing (that would be 2, I think). Why can't one "simply" compare the T(FF) and T(compressed FF) by getting the norm of the differences of the resulting arrays? We should have them for both as output of the model, right? I'm probably missing something.

**Comment by sampotter** [comment]
> Also, why can't one "simply" compare the T(FF) and T(compressed FF) by getting the norm of the differences of the resulting arrays? We should have them for both as output of the model, right? I'm probably missing something.

Yes, we can do this, and we will do this. We could make a plot of this value for varying compression tolerance and mesh size; or maybe better, just a table of values, since the paper is going to become overburdened with plots.

The plots above in the case where the meshes are the same size and T is directly comparable are just for visualization purposes (unlike the third plot, where I try to compare directly the fields obtained from different meshes). I think it's helpful to get some visual sense of the error; where it is largest, whether there is some spatial correlation, etc.

Does that answer your question?

**Comment by steo85it** [comment]
Mmm, not really ... what I meant is that we have T(FF,x,y,z,t) and T(cFF,x,y,z,t) and we can compare and plot those, with associated coordinates to get the same result that you plotted above (I think).

**Comment by steo85it** [comment]
We could dump the output T to a GTiff, then read them with whatever tool/library we want and compute differences (at least this is what I'm doing to generate the plot below, different but along the same lines and with T obtained from the same output).
![immagine](https://user-images.githubusercontent.com/29377066/151235826-cb7870df-d1fe-4c97-bb24-644af16755d6.png)
One would have to decide which coordinates to associate to each T (or what T to associate to each vertex, I guess) - probably that's "clearer" in your approach?

**Comment by steo85it** [comment]
Also, are your plots in stereo projection, or what are the axes coordinates? It would be good to have those in stereo, for the paper (either by keeping the mesh itself in stereo, and just converting to cartesian for the illumination computations - or else by reprojecting before plotting).

**Comment by sampotter** [comment]
> But ok, the issue is to which x,y do we associate T (vertices? centers of facets?).

This has a clear answer. In our discretization of the radiosity integral equation, we use constant basis functions. So, we think of `T` as being a piecewise constant function defined over the triangulation (ditto the insolation and the radiance). This is not well-defined over edges and vertices (which incident face should we take the `T` value from?). The way I resolve this is simple: just use whatever triangle the raytracer tells me I hit. In practice, CGAL never says, "oh, you hit an edge---which triangle do you want?". I don't know how it resolves this ambiguity and I don't really care.

> Also, are your plots in stereo projection, or what are the axes coordinates?

The axes currently are (x, y) Cartesian. I set up a grid of rays beneath the crater with ray directions all equal to (0, 0, 1). The origin of each ray is of the form `(x + h*i, y + h*j, z)`, for fixed x, y, and z values.

Let me think about how best to do a plot like this in stereo projection.

**Comment by sampotter** [comment]
OK, plotting in stereo was actually pretty easy:

![image](https://user-images.githubusercontent.com/6035363/151390288-11bee878-d5e8-4c1b-bd1f-3e01bf41cf8f.png)

Simple way to do this:
- proceed as before with everything in Cartesian
- when making the meshes initially, also save out the (x, y) stereo coordinates of the vertices of the mesh (so you have two sets of vertices: stereo & Cart)
- use the stereo vertices and the face indices to get a triangulation in stereo coordinates

For this plot I just made a `CgalTrimeshShapeModel` to look up hit points for a grid of rays. But there's probably some scipy or matplotlib convenience function that will allow you to make this same plot...

**Comment by steo85it** [comment]
Yes, that's the "opposite" of what I was suggesting or usually doing (but it works all the same): one just associates different vertices coordinates to the same indexes (and hence facets).
Do we then get the same result if we associate T to the center P of each triangle? In that case, we can easily do what I was suggesting yesterday (producing GTiffs and then read and compare them with whatever tools, or directly have raster xyT in memory and make computations among them, differences or normed differences or whatever we want). If we always use the same mesh, we don't even need to interpolate, else we might need to. Or do you think that with different meshes (do we really need to compare among them? Or just results of different FF based on the same mesh) your approach would still be better/faster/more accurate?

**Comment by sampotter** [comment]
> Do we then get the same result if we associate T to the center P of each triangle?

You can think of associating T to the center of each triangle if you like.

I find it helpful to think of T as a piecewise constant function defined on the facets of a piecewise linear surface in 3D.

The two can be converted back and forth in the obvious way.

> In that case, we can easily do what I was suggesting yesterday (producing GTiffs and then read and compare them with whatever tools, or directly have raster xyT in memory and make computations among them, differences or normed differences or whatever we want). If we always use the same mesh, we don't even need to interpolate, else we might need to. Or do you think that with different meshes (do we really need to compare among them? Or just results of different FF based on the same mesh) your approach would still be better/faster/more accurate?

There are a few things.

I find the GeoTIFFs hard to work with because I haven't learned the format. They slow me down a lot.

If we want to think of T as a list of point values defined at the centroid of each triangle, then we can just work with these values directly (i.e. with the numpy array that is the result of e.g. compute_steady_state_temp). Indeed, if we always use the same mesh, no interpolation is necessary. And the thing I'm doing to make the plots above isn't necessary, either.

What I'm doing above does let us compare between different meshes. I am not at all sure this is a sensible thing to do. I think we should probably just leave it alone for now.

That said, I think it is helpful to make image plots like the above to give a qualitative sense of the solution. I like this approach because it computes a separate value for each pixel in an image. If we treat T as a bunch of point values, it isn't clear to me how we make such a plot. One way to go would be to make a scatter plot, but I think this is a bit confusing and unpleasant to look at. The pictures I made above are clear: they are just the result of taking a picture of T (in its "piecewise constant function on triangle mesh in 3D" mode).

Please let me know if I'm missing something in your previous response.

**Comment by steo85it** [comment]
Great, thanks for the clarifications! Storing stereo coordinates and associated T in arrays (with more or less complexity), we should be able to plot maps such as this one (it shows T differences among epochs/cycles, but it's along the same lines)
![immagine](https://user-images.githubusercontent.com/29377066/151404931-b2520948-474b-4754-8ba1-2673fd7eb619.png)
I need to try with the gerlache's output, but it should work, I think ...

**Comment by sampotter** [comment]
Can you explain the plot a bit and how it differs from the plot I'm making? I need some more context.

Why is there "shot noise" (white pixels) throughout?

**Comment by steo85it** [comment]
Sure, sorry. It's quite close to what you are doing (which is good) but based on those T(t,z,x,y) arrays I was mentioning, which might make it easier to compare and compute differences between different outputs and configurations. Those arrays can be exported to GTiffs (if useful for storing, avoiding pickle issues), but also simply "used" as arrays within the script.
Now, if you are satisfied with your solution, that's perfectly fine (as you pointed out, the results are similar). If not, this might be an alternative approach.

> Why is there "shot noise" (white pixels) throughout?

Those are PSRs which I intentionally removed from the whole computation. They should be like this, not an artifact. :)

**Comment by sampotter** [comment]
OK. How do you make a raster for that plot? I'm still confused about that part.

**Comment by steo85it** [comment]
ok, let me try with an output of gerlache and see if/how it works, and we can better compare and discuss. :)

**Comment by steo85it** [comment]
Nope, more difficult than I expected (with the issue being that the number of datapoints in the initial raster is not conserved to the final mesh, and hence to the final T.shape). A pity, it would have been convenient for I/O and computations. It might still work within the selected region (where the number of vertices/facets is conserved, but maybe not worth spending too much time.

**Comment by sampotter** [comment]
OK, no problem. We have a way of making the necessary plots for now which is enough for the current paper. Definitely the GeoTIFF format seems useful for the future.

**Comment by steo85it** [comment]
@sampotter I think there is an issue in the "stereo vertices" of your mesh. For example, when you compare the stereographic coordinates of `ldem_87s_50mpp` (in meters)
![image](https://user-images.githubusercontent.com/29377066/155633131-be7871ce-a80c-40b7-aee8-2199c6ebf837.png)
with the stereo coordinates (in km) of the deGerlache clip from earlier in the conversation (https://github.com/sampotter/python-flux/issues/55#issuecomment-1023347306):
![image](https://user-images.githubusercontent.com/6035363/151394585-93d2a857-bbb9-4e16-9b1c-235875bc170c.png)
one sees that they fit with each other only if x=y and y=-x. Any idea where the issue could come from? The stereo transformation itself seems to be ok, so it might be in the meshing/raster import step.

**Comment by sampotter** [comment]
I would say it is quite possible I did something silly when reading the data in from Mike's GeoTIFF file. I am not sure exactly where the problem is, but I do recall having to screw around with the axes in the image plots to make them match.

**Comment by sampotter** [comment]
IIRC, Mike's GeoTIFF file contains (buried within it somewhere), a packed 1D array of 64-bit floats corresponding to x coordinates, ditto for y coordinates, and then a packed 2D array of z values. (Maybe the x and y floats are also 2D arrays, but pretty sure it was 1D...)

I am not sure how the 2D array of z values is ordered. Should either row major or column major. If we can figure that out, I should easily be able to make my getz function consistent with it. Hopefully that will fix the bug.

**Comment by steo85it** [comment]
(I just noticed that xc, yc are not only switched w.r.t. the usual stereo coordinates, but rather `xc=-y` and `yc=x` - just not visible for deGerlache, since y=0)

**Comment by steo85it** [comment]
> IIRC, Mike's GeoTIFF file contains (buried within it somewhere), a packed 1D array of 64-bit floats corresponding to x coordinates, ditto for y coordinates, and then a packed 2D array of z values. (Maybe the x and y floats are also 2D arrays, but pretty sure it was 1D...)
By using
```
import rioxarray as rio
rds = rio.open_rasterio(tif_path)
x = rds.coords['x'].values
y = rds.coords['y'].values
```
you should be able to retrieve those.
